### ISSUE TITLE
React application loading callback

### ISSUE THREAD

**Issue by seekhow** [aliyun/alibabacloud-console-os#27]
"@alicloud/console-os-react-app": "~0.3.6"
希望@alicloud/console-os-react-app Application组件暴露应用加载loading以便自定义loading效果

**Comment by royIdoodle** [comment]
可以试试利用`appDidMount`生命周期来实现loading效果

**Comment by Boelroy** [comment]
已经发布了，目前 react-app 已经支持。 https://github.com/aliyun/alibabacloud-console-os/commit/f129e7a6cbd56dee13c056844a19cf8e2cbff943

```javascript
import Application from '@alicloud/console-os-react-app'
<Application 
  loading={<div>loading</div>}
/>
```
