### ISSUE TITLE
关于webpack3的支持

### ISSUE THREAD

**Issue by royIdoodle** [aliyun/alibabacloud-console-os#29]
## 背景
目前子应用如果是通过`webpack`构建的话，可以通过引入插件的形式来实现，[文档地址](https://aliyun.github.io/alibabacloud-console-os/guides/react#%E5%AD%90%E5%BA%94%E7%94%A8)
但是实际开发中，很多项目（遗产项目）是通过`webpack3`来实现的，目前引入的`@alicloud/console-toolkit-plugin-os`并不支持`webpack3`

## 期望
希望可以使`@alicloud/console-toolkit-plugin-os`支持`webpack3`，这样可以降低接入成本，否则要子项目做wepack的版本迁移

**Comment by Boelroy** [comment]
目前已经支持完了，但是还没发布，有个已知问题看是否能接受， 可以看一下 PR https://github.com/aliyun/alibabacloud-console-os/pull/36

**Comment by royIdoodle** [comment]
> 目前已经支持完了，但是还没发布，有个已知问题看是否能接受， 可以看一下 PR #36

可以的，多谢~

**Comment by Boelroy** [comment]
已经发布
