### ISSUE TITLE
运行宿主项目 和子项目 Warning: 警告

### ISSUE THREAD

**Issue by lany9527** [aliyun/alibabacloud-console-os#4]
如下图：
运行宿主项目 和子项目 报 Warning: 警告，请问有什么解决方式，
![image](https://user-images.githubusercontent.com/19483798/81467745-5bc3a500-920d-11ea-8ed0-7f732ee4f335.png)

**Comment by Boelroy** [comment]
这个 warning 是由于 ConsoleOS 里面使用了 React.createElement("body") ，这个操作是为了创建一个 body 然后给到沙箱，作为沙箱中的body. 目前在沙箱开启的情况下暂时还没办法消除。不过在沙箱关闭的时候这个倒是不应该出现干扰，这个后续迭代这边可以优化掉。

当前这个warning 目前并不会影响使用，并且只会在 dev 环境才会报出，production 应该不会报出。
