### ISSUE TITLE
子应用打包之后，包裹器样式对第三方库没有生效

### ISSUE THREAD

**Issue by ayiaq1** [aliyun/alibabacloud-console-os#42]
![image](https://user-images.githubusercontent.com/3860498/92097957-3c2f3880-ee0b-11ea-9c51-ac244c43e528.png)

main.js:
```
import Vue from "vue";
import App from "./App.vue;
import "ant-design-vue/dist/antd.css";
import Antd from "ant-design-vue";
import router from "./router";
import { mount } from "@alicloud/console-os-vue-portal";
Vue.use(Antd);
export default mount({
  el: "#app",
  router,
  render: (h) => h(App)
});
```

**Comment by ayiaq1** [comment]
场景：宿主应用使用的element-ui
在弹框内的为子应用
第三方用的ant-vue
![image](https://user-images.githubusercontent.com/3860498/92099596-4b16ea80-ee0d-11ea-85c8-da81bbeb239c.png)
![image](https://user-images.githubusercontent.com/3860498/92099653-5b2eca00-ee0d-11ea-80e6-2b277c31731d.png)

**Comment by Boelroy** [comment]
是这样的 你如果想写的化 你要以  <os-example-vue></os-example-vue> 这样自定义节点来包裹你应用的元素，这样才会生效
