### ISSUE TITLE
dev模式加载资源报404

### ISSUE THREAD

**Issue by wangcherry** [aliyun/alibabacloud-console-os#45]
资源在manifest生成是正确的 '//dev.g.alicdn.com/...' ，但是在load静态资源时，路径被处理成 'dev.dev.g.alicdn.com'。

建议在 getRealUrl 方法里，urlStr.replace('g.alicdn.com', 'dev.g.alicdn.com'); 改为 urlStr.replace('//g.alicdn.com', '//dev.g.alicdn.com');

**Comment by Boelroy** [comment]
fixed https://github.com/aliyun/alibabacloud-console-os/commit/328f762a8d46a9bb54a160ded62e10e5f58c4b82
